### ISSUE TITLE
Crash in synchronization

### ISSUE THREAD

**Issue by ge0rg** [horazont/muchopper#7]
After some minutes of running the bot, this happens:

```
INFO     muchopper.client.bot.mirror.MirrorClient init-sync: remote knows 4940 entries, downloading (this may take a moment -- turn on debug logging for detailed prog
ress)...
INFO     muchopper.client stopping stream
DEBUG    muchopper.client.StanzaStream sending stop signal to task
DEBUG    muchopper.client.StanzaStream task terminating, rescuing stanzas and clearing handlers
ERROR    muchopper.client main failed
Traceback (most recent call last):
  File "/home/mucsearch/.local/lib/python3.5/site-packages/aioxmpp/node.py", line 824, in _on_main_done
    task.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/mucsearch/.local/lib/python3.5/site-packages/aioxmpp/node.py", line 989, in _main
    yield from self._main_impl()
  File "/home/mucsearch/.local/lib/python3.5/site-packages/aioxmpp/node.py", line 958, in _main_impl
    features)
  File "/home/mucsearch/.local/lib/python3.5/site-packages/aioxmpp/node.py", line 908, in _negotiate_stream
    yield from self.before_stream_established()
  File "/home/mucsearch/.local/lib/python3.5/site-packages/aioxmpp/callbacks.py", line 616, in fire
    keep = yield from coro(*args, **kwargs)
  File "/home/mucsearch/muchopper/muchopper/bot/mirror.py", line 352, in _on_stream_established
    batches = list(chop_to_batches(existing_ids, 32))
  File "/home/mucsearch/muchopper/muchopper/bot/mirror.py", line 26, in chop_to_batches
    for _, items in itertools.group(iterable, lambda x: clock()):
AttributeError: module 'itertools' has no attribute 'group'
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mucsearch/muchopper/muchopper/bot/__main__.py", line 2, in <module>
    muchopper.bot.cli.main()
  File "/home/mucsearch/muchopper/muchopper/bot/cli.py", line 119, in main
    loop.run_until_complete(amain(loop, args, cfg))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/home/mucsearch/muchopper/muchopper/bot/cli.py", line 66, in amain
    await daemon.run()
  File "/home/mucsearch/muchopper/muchopper/bot/daemon.py", line 330, in run
    async with self._client.connected():
  File "/home/mucsearch/.local/lib/python3.5/site-packages/aioxmpp/node.py", line 1630, in __aenter__
    yield from conn_future
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/home/mucsearch/.local/lib/python3.5/site-packages/aioxmpp/node.py", line 824, in _on_main_done
    task.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/mucsearch/.local/lib/python3.5/site-packages/aioxmpp/node.py", line 989, in _main
    yield from self._main_impl()
  File "/home/mucsearch/.local/lib/python3.5/site-packages/aioxmpp/node.py", line 958, in _main_impl
    features)
  File "/home/mucsearch/.local/lib/python3.5/site-packages/aioxmpp/node.py", line 908, in _negotiate_stream
    yield from self.before_stream_established()
  File "/home/mucsearch/.local/lib/python3.5/site-packages/aioxmpp/callbacks.py", line 616, in fire
    keep = yield from coro(*args, **kwargs)
  File "/home/mucsearch/muchopper/muchopper/bot/mirror.py", line 352, in _on_stream_established
    batches = list(chop_to_batches(existing_ids, 32))
  File "/home/mucsearch/muchopper/muchopper/bot/mirror.py", line 26, in chop_to_batches
    for _, items in itertools.group(iterable, lambda x: clock()):
AttributeError: module 'itertools' has no attribute 'group'
DEBUG    muchopper.client.StanzaStream iq request coroutine unregistered: type=<IQType.GET: 'get'>, payload=<class 'aioxmpp.disco.xso.InfoQuery'>
DEBUG    muchopper.client.StanzaStream iq request coroutine unregistered: type=<IQType.GET: 'get'>, payload=<class 'aioxmpp.disco.xso.ItemsQuery'>
DEBUG    muchopper.client.StanzaStream iq request coroutine unregistered: type=<IQType.GET: 'get'>, payload=<class 'muchopper.bot.xso.Search'>
DEBUG    muchopper.client.StanzaStream iq request coroutine unregistered: type=<IQType.GET: 'get'>, payload=<class 'aioxmpp.version.xso.Query'>
Exception ignored in: <generator object Queue.get at 0x7f4e006bd7d8>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/queues.py", line 169, in get
  File "/usr/lib/python3.5/asyncio/futures.py", line 246, in cancel
  File "/usr/lib/python3.5/asyncio/futures.py", line 261, in _schedule_callbacks
  File "/usr/lib/python3.5/asyncio/base_events.py", line 572, in call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 357, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <generator object Queue.get at 0x7f4e006bd620>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/queues.py", line 169, in get
  File "/usr/lib/python3.5/asyncio/futures.py", line 246, in cancel
  File "/usr/lib/python3.5/asyncio/futures.py", line 261, in _schedule_callbacks
  File "/usr/lib/python3.5/asyncio/base_events.py", line 572, in call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 357, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <generator object Queue.get at 0x7f4e006bd468>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/queues.py", line 169, in get
  File "/usr/lib/python3.5/asyncio/futures.py", line 246, in cancel
  File "/usr/lib/python3.5/asyncio/futures.py", line 261, in _schedule_callbacks
  File "/usr/lib/python3.5/asyncio/base_events.py", line 572, in call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 357, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <generator object Queue.get at 0x7f4e006bd2b0>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/queues.py", line 169, in get
  File "/usr/lib/python3.5/asyncio/futures.py", line 246, in cancel
  File "/usr/lib/python3.5/asyncio/futures.py", line 261, in _schedule_callbacks
  File "/usr/lib/python3.5/asyncio/base_events.py", line 572, in call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 357, in _check_closed
RuntimeError: Event loop is closed
```

**Comment by horazont** [comment]
So this is due to things having been committed which should never have been. I fixed them in 064bd2c568b589e870ce5bef0c774e218f4bc351. Hopefully that does the trick, if not, feel free to reopen.
